TEAM_COLORS = {
    'ANA': '#003263',
    'ARI': '#A71930',  
    'ATL': '#CE1141',  
    'BAL': '#DF4601',  
    'BOS': '#BD3039',  
    'CHC': '#0E3386',  
    'CHW': '#27251F',  
    'CIN': '#C6011F',  
    'CLE': '#00385D',  
    'COL': '#333366',  
    'DET': '#0C2340',
    'FLA': '#009CA6',
    'HOU': '#002D62',  
    'KCR': '#004687',  
    'LAA': '#003263',  
    'LAD': '#005A9C',  
    'MIA': '#00A3E0',  
    'MIL': '#12284B',  
    'MIN': '#002B5C',  
    'MON': '#003087',
    'NYM': '#002D72',  
    'NYY': '#003087',  
    'ATH': '#003831',
    'OAK': '#003831',
    'PHI': '#E81828',  
    'PIT': '#27251F',  
    'SDP': '#2F241D',  
    'SFG': '#FD5A1E',  
    'SEA': '#0C2C56',  
    'STL': '#C41E3A',  
    'TBR': '#092C5C',  
    'TBD': '#092C5C',
    'TEX': '#003278',  
    'TOR': '#134A8E',  
    'WSN': '#AB0003'
}

def get_team_colors(teams):
    return {team: TEAM_COLORS.get(team, '#888888') for team in teams}

TEAM_NAMES = {
    'ANA': 'Los Angeles Angels of Anaheim',
    'ARI': 'Arizona Diamondbacks',
    'ATL': 'Atlanta Braves',
    'BAL': 'Baltimore Orioles',
    'BOS': 'Boston Red Sox',
    'CHC': 'Chicago Cubs',
    'CHW': 'Chicago White Sox',
    'CIN': 'Cincinnati Reds',
    'CLE': 'Cleveland Guardians',
    'COL': 'Colorado Rockies',
    'DET': 'Detroit Tigers',
    'FLA': 'Floria Marlins',
    'HOU': 'Houston Astros',
    'KCR': 'Kansas City Royals',
    'LAA': 'Los Angeles Angels',
    'LAD': 'Los Angeles Dodgers',
    'MIA': 'Miami Marlins',
    'MIL': 'Milwaukee Brewers',
    'MIN': 'Minnesota Twins',
    'NYM': 'New York Mets',
    'NYY': 'New York Yankees',
    'ATH': 'Sacramento Athletics',
    'OAK': 'Oakland Athletics',
    'PHI': 'Philadelphia Phillies',
    'PIT': 'Pittsburgh Pirates',
    'SDP': 'San Diego Padres',
    'SFG': 'San Francisco Giants',
    'SEA': 'Seattle Mariners',
    'STL': 'St. Louis Cardinals',
    'TBD': 'Tampa Bat Devil Rays',
    'TBR': 'Tampa Bay Rays',
    'TEX': 'Texas Rangers',
    'TOR': 'Toronto Blue Jays',
    'WSN': 'Washington Nationals',
    'MON': 'Montreal Expos',
}